### ISSUE TITLE
gcalendar doesn't work anymore

### ISSUE THREAD

**Issue by porcaror** [slgobinath/gcalendar#4]
Hi,
I'm using Manjaro cinnamon. After the last update gcalendar disapperead from the desktop.
Now if I launch gcalendar in a terminal, I have the following errors:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rsa 4.6 (/usr/lib/python3.8/site-packages), Requirement.parse('rsa<4.1,>=3.1.4'), {'gcalendar'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gcalendar", line 33, in <module>
    sys.exit(load_entry_point('gcalendar==0.3', 'console_scripts', 'gcalendar')())
  File "/usr/bin/gcalendar", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/gcalendar/__main__.py", line 30, in <module>
    from gcalendar.gcalendar import GCalendar
  File "/usr/lib/python3.8/site-packages/gcalendar/gcalendar.py", line 22, in <module>
    from googleapiclient import discovery
  File "/usr/lib/python3.8/site-packages/googleapiclient/discovery.py", line 49, in <module>
    import google.api_core.client_options
  File "/usr/lib/python3.8/site-packages/google/api_core/__init__.py", line 20, in <module>
    from pkg_resources import get_distribution
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rsa<4.1,>=3.1.4' distribution was not found and is required by gcalendar

What can I do?
Thanks a lot in advance
Roberto

**Comment by slgobinath** [comment]
Hi,

Can you try this solution https://github.com/slgobinath/gcalendar/issues/1

Please let me know if this helps

**Comment by porcaror** [comment]
Thank you very much for your suggestion. Unfortunately Manjaro is an Arch
derivative so it is not very simple to try to make a downgrade you a
previous version. Any other suggestion?
Thanks a lot for your help.
Roberto

**Comment by slgobinath** [comment]
I've removed the restriction at `gcalendar` level. Could you please test the latest changes from the source code and let me know if that fixes the problem?
If so, I will release a new version with the fix.

To test from source, please use these commands.
```
git clone https://github.com/slgobinath/gcalendar.git
cd gcalendar
python3 -m gcalendar
```

Thanks

**Comment by porcaror** [comment]
Hi.

Thank you very much.

I have no problem following your instruction.

After it seems to work. If I right click in the gcalendar area I can access my calendar.

Roberto

**Comment by porcaror** [comment]
Hi. Sorry to disturb you again. Just a question. When do you think the new
calendar aur package that solves the problem will be ready?
Thank you very much.
Roberto

**Comment by slgobinath** [comment]
Hi Roberto,

Please accept my apologies I forgot to release the fix.
I just released the new version with the fix. Please check the updated version.
Thank you for your patience.
